### PR TITLE
Risk mitigation

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
I see you are finalising the code, Ahmad, that’s great! The branch has merge conflicts with master that have to be resolved.

**Comment by albertohata** [comment]
> I see you are finalising the code, Ahmad, that’s great! The branch has merge conflicts with master that have to be resolved.

Hi @ahmadterra is it possible to check this conflict in order to proceed with the merging?

**Review by berezovskyi — COMMENTED** [review]
I think all shelf-related things shall be undone: the makefile reverted and the webapp-twin-shelf folder removed

**Comment by ahmadterra** [comment]
I have undone the shelf-related files that I modified to 157e05f, is there any other files that need to be fixed/undone?

**Comment by berezovskyi** [comment]
@ahmadterra you are still modifying a bunch of java files. Please see under the Changes tab.

**Comment by berezovskyi** [comment]
thanks! just merged :)

**Pull request merged**
