### PR TITLE
Planner reasoner instructions and oslc_prolog -> its own github repo

### PR DESCRIPTION
**Pull request by likelion**
Added `docker-compose` support for `planner_reasoner` (addressing #66).
Added Postman collection with example PDDL handling requests.
Moved `oslc_prolog` library to [https://github.com/EricssonResearch/oslc_prolog](https://github.com/EricssonResearch/oslc_prolog).

### CODE REVIEW

**Comment by berezovskyi** [comment]
Wow, that was fast! Thank you so much! I am not able to run it just yet:

```
~/kth/scott/scott/planner_reasoner (likelion-patch-8 ✘)✭ ᐅ docker build -t scott-planner .
...
~/kth/scott/scott/planner_reasoner (likelion-patch-8 ✘)✭ ᐅ docker run scott-planner
% Updating GIT version stamps in the background.
% Config: /opt/PlannerServer/config-enabled/010-packs.pl
% Config: /opt/PlannerServer/config-enabled/500-oslc_prolog.pl
% Loaded RDF manifest file:///opt/PlannerServer/cpack/oslc_prolog/rdf/base/Manifest.ttl
% Loading 1 files using 1 threads ...
% Parsed "oslc.rdf" in 0.01 sec; 480 triples
% Loading 1 files using 1 threads ...
% Parsed "oslc_shapes.ttl" in 0.00 sec; 882 triples
% Config: /opt/PlannerServer/config-enabled/700-planner_reasoner.pl
% Loaded RDF manifest file:///opt/PlannerServer/cpack/planner_reasoner/rdf/base/Manifest.ttl
% Loading 1 files using 1 threads ...
% Parsed "pddl.ttl" in 0.00 sec; 551 triples
% Loading 1 files using 1 threads ...
% Parsed "planner.ttl" in 0.00 sec; 45 triples
% Loading 1 files using 1 threads ...
% Parsed "pddl_example.ttl" in 0.00 sec; 219 triples
% Config: /opt/PlannerServer/config-enabled/config.pl
% Config: /opt/PlannerServer/config-enabled/network.pl
% Config: /opt/PlannerServer/config-enabled/pengines.pl
% Config: /opt/PlannerServer/config-enabled/store.pl
% Config: /opt/PlannerServer/config-enabled/zlib.pl
ERROR: /opt/PlannerServer/settings.db:5:26: Syntax error: Illegal start of term
% Started server at http://localhost:3020/
% Loaded 0 graphs (0 triples) in 0.00 sec. (95% CPU = 0.00 sec.)

% halt
```

Line 5 is `setting(http:public_port, %PUBLIC_PORT%).` ~~I think it is missing the quotes around the port placeholder.~~ Nope, my fix didn't work as I now get `Type error: `integer' expected, found `'3020'' (an atom)`. You are my hope now :)

**Review by berezovskyi — CHANGES_REQUESTED** [review]
Thanks a lot! I left a comment that details failed Docker build output.

**Comment by likelion** [comment]
try `docker-compose up` instead :)

**Review by berezovskyi — APPROVED** [review]

**Comment by berezovskyi** [comment]
Thanks a lot, I have also added some 101 to the README.

**Pull request merged**
