### PR TITLE
Set CPACK loading priority

### PR DESCRIPTION
**Pull request by likelion**
When multiple dependent CPACKs are loaded the priority of loading is important. It is ensured by sorting of the config file names.

### CODE REVIEW

**Comment by berezovskyi** [comment]
@likelion do you think a comment somewhere about the loading rule (that the 500 module shall be always loaded before 700 module) would be beneficial?

**Comment by likelion** [comment]
Definitely! It will be part of the README file describing the usage of OSCL lib.

**Review by konstantino — APPROVED** [review]
ok, so each module needs to be prefixed with a priority number. quick and dirty.

**Comment by konstantino** [comment]
Still, it would have been nicer if the priority was decoupled from the name of the module #iapproovedtoofast

**Comment by berezovskyi** [comment]
I still don't see the explanation which module needs to be in which order and why. But doing this through the filename is OK as a quick fix, as long as we can understand it later.

**Comment by likelion** [comment]
Guys, this is the way ClioPatria works, I cannot do anything about it, took some time to figure it out also :) We can affect the situation through the official open source channel [ClioPatria/ClioPatria](https://github.com/ClioPatria/ClioPatria).

**Pull request merged**
