### PR TITLE
Define a mission ontology (with OSLC shapes)

### PR DESCRIPTION
**Pull request by berezovskyi**
We started with the following pseudocode (a mix of a YAML & Ruby):

```
Mission:
 - responseTimout: xsd:duration 0..1
 - missionDeadline: xsd:duration 0..1
 # - missionExpiration: xsd:datetime 0..1
 - goal: Goal 1..*

Goal:{}

MoveGoal < Goal:
 - selector: Selector 1..1
 - destination: Location 1..1

 DirectSelector < Selector:
 - item: Resource 1..*

CountedTypeSelector < Selector:
- itemType: rdf:Class 1..1
- count: xsd:integer 1..1

 WildcardTypeSelector < Selector:
  - itemType: rdf:Class 1..1

 CompositeSelector < Selector:
 # has union semantics
  - selector: Selector 1..*

LocationSelector < Selector:
# Example
# CompositeSelector
# - DirectSelector A1
# - LocationSelector
#     - CountedTypeSelector A 3
#     - location S1
- selector: Selector 1..1
- location: Location 1..1
```

### CODE REVIEW

**Comment by berezovskyi** [comment]
Here is an example for a following mission:

> Move 2 pairs of blue jeans from the shelf no. 2 and all milk from the shelf no. 3 to the shelf no. 1 in less than 20 minutes. The planner shall not take more that 2 minutes 30.5 seconds to generate this plan.

```turtle
:sampleMission a :Mission;
  :goal [ a :MoveGoal;
          :selector [ a :CompositeSelector;
                      :selector [a :LocationSelector;
                                 :location <shelf2> ;
                                 :selector [ a :TypeSelector ;
                                             :itemType <BlueJeans>;
                                             :count 2
                                           ] ,
                      :selector [ a :LocationSelector;
                                  :location <shelf3> ;
                                  :selector [ a :WildcardSelector ;
                                              :itemType <Milk>
                                            ]
                                ]
                    ]
          :destination <shelf1>
  ] ;
  :responseTimeout "PT2M30.5S"^^xsd:duration ; # 2min 30.5s to produce a plan
  :missionDeadline "PT20M"^^xsd:duration . # 20 min to execute the plan
```

**Comment by berezovskyi** [comment]
cc @kraiser

**Review by likelion — APPROVED** [review]

**Comment by swarupmohalik** [comment]
Will the following lead to simple syntax and simpler shapes?

```turtle
:sampleMission a :Mission ;

  /* move object obj1 at location sloc12 to destination cbout1 */
  :goal [ a :MoveGoal ;
          :selector [ a :InstanceSelector ;
                      :itemId <obj1>
                    ] ,
          :source   [ a :Location ;
                      :locationId <sloc12>
                    ] ,
          :destination [ a :Location ;
                         :locationId <cbout1>
                       ]
        ],

  /* move object obj2 to destination cbout1 */
  :goal [ a :MoveGoal;
          :selector [ a :InstanceSelector;
                      :itemId <obj2>
                    ] ,
          :source [ a :Location;
                    :locationId <ANY> // wildcard - wherever
                   ] ,
          :destination [ a :Location;
                         :locationId <cbout1>
                       ]
        ],

  /* move 2 Bluejeans objects (no matter where they are now) to the cbout1 location
  :goal  [ a :MoveGoal ;
          :selector [ a :TypeSelector
                      :itemType <BlueJeans> ;
                      :count 2
                    ] ,
          :source [ a :Location ;
                    :locationId <ANY> //wildcard - any source location
                  ] ,
          :destination [ a :Location ;
                         :locationId <cbout1>
                       ]
        ] ,

  /* move 2 Bluejeans objects from shelf1 to the cbout1 location
  :goal  [ a :MoveGoal ;
          :selector [ a :TypeSelector
                      :itemType <BlueJeans> ;
                      :count 2
                    ] ,
          :source [ a :Location ;
                     :locationId <Shelf1>
                  ] ,
          :destination [ a :Location ;
                         :locationId <cbout1>
                        ]
        ] ,
]
```

**Comment by likelion** [comment]
I did some cleanup, will follow with comments later...

**Comment by likelion** [comment]
I think the reasons we went for combining selector and source are:
 
- to combine items of different types and quantities from different locations (with clear selection semantics) when they have the same destination
- to take advantage of the fact that when we know exact instance ID we can infer its source location (which the user may not know at the time of request)
- to avoid superficial "ANY" location

So your file in our definition looks like (also more compact):

```turtle
:sampleMission a :Mission;
  :goal [ a :MoveGoal;
          :selector [ a :CompositeSelector ;
                      :selector [ a :DirectSelector ;
                                  :item <obj1> ,
                                        <obj2>
                                ] ,
                      :selector [ a :TypeSelector ;
                                  :itemType <BlueJeans> ;
                                  :count 2
                                ] ,
                      :selector [ a :LocationSelector ;
                                  :location <Shelf1> ;
                                  :selector [ a :TypeSelector ;
                                              :itemType <BlueJeans>
                                              :count 2
                                            ]
                                ]
                    ]
          :destination <cbout1>
  ] ;
  :responseTimeout "PT2M30.5S"^^xsd:duration ; # 2min 30.5s to produce a plan
  :missionDeadline "PT20M"^^xsd:duration . # 20 min to execute the plan
```

**Comment by likelion** [comment]
We should probably move this specification to some kind of MOO project, what do you think?

**Review by konstantino — APPROVED** [review]

**Comment by swarupmohalik** [comment]
The syntax does not seem to be able to specify 
"Any N objects" (of arbitrary type)

The wildcardSelector needs a type. 
We perhaps need numWildcardSelector which needs only a number.
The current wildcardSelector can be named typeWildcardSelector.

**Comment by berezovskyi** [comment]
I don't think it is a good feature to move N items of whatever in the warehouse, @swarupmohalik.

We already have a `TypeSelector` that allows you to pick N items of a given type, like 10 IKEA chairs.

Any reason for allowing to move "whatever"?

**Comment by berezovskyi** [comment]
@eanevul did you have a chance to take a look at this?

**Comment by berezovskyi** [comment]
Okay @swarupmohalik, we just had a talk with @likelion and decided that we can modify the selector hierarchy to work the following way. There will be three selector types in the beginning:

* CountSelector w/ `count: int 1..1` property
* TypeSelector w/ `itemType: rdf:class 1..1` property
* LocationSelector w/`location: geonames:feature 1..1` property

Each of those will also allow a child `selector: Selector 1..1` property to perform as a source for selection. If none is provided, the whole warehouse is a source.

Finally, the CompositeSelector is left untouched, with its `selectors: Selector 1..*` property to allow a union of the selector results. The same goes for the DirectSelector.

Here are a few examples of how these selectors can be used.

**Any N objects**

```turtle
_:sel a CountSelector;
    count "N"^^xsd:integer .
```

**N objects from shelf A and M objects from shelf B**

```turtle
_:sel a CompositeSelector;
  selectors [
    a CountSelector ;
    count "N"^^xsd:integer ;
    selector [
      a LocationSelector ;
      location _:shelfA .
    ] ;
  selectors [
    a CountSelector ;
    count "M"^^xsd:integer ;
    selector [
      a LocationSelector ;
      location _:shelfB .
    ] ;
  ] .
```

**move object obj1 at location sloc12 to destination cbout1**

```turtle
_:sel a DirectSelector;
  item _:obj1 .
```

**move object obj2 to destination cbout1**

The same as above because the object id is unique across the warehouse.

**move 2 Bluejeans objects (no matter where they are now) to the cbout1 location**

```turtle
_:sel a CountSelector ;
  count "2"^xsd:integer ;
  selector [
    a TypeSelector ;
    itemType _:Bluejeans .
  ] .
```

**move 2 Bluejeans objects from shelf1 to the cbout1 location**

```turtle
_:sel a CountSelector ;
  count "2"^xsd:integer ;
  selector [
    a TypeSelector ;
    itemType _:Bluejeans .
    selector [
      a LocationSelector ;
      location _:shelf1 .
    ]
  ] .
```

So you should read the selectors inside out: look at the shelf1, find Bluejeans and pick 2 of them. In terms of the selectors, if there is a `selector` property, take its output as an input to the parent selector. If there is none, assume there is a wildcard selector. In other words, if I would not have added the LocationSelector to the example above, it would have taken 2 Bluejeans objects from anywhere in the warehouse.

---

I used different names for the `selector` and `selectors` properties as they have different cardinality and it will be easier to implement this with our OSLC tools than try assigning different semantics to the same property when applied on a different resource. @jadelkhoury, am I right?

**Comment by swarupmohalik** [comment]
Andrii, you have a point regarding "N objects of any type". I was thinking of all possible combination of the three features - type, number and source location. But the new model is good since for example, if the MOO_Manager knows that there are items of a single type in the warehouse, it may not elaborate and just specify "move n objects". One can put a restriction on the missions, but the generalization is cleaner.

one more thing:
Does the above result in RDF "trees" as in the following picture?
Are there cases where the internal nodes can have more than one "selector" branches?
If not, the recursive structure seems overweight. I would go for a flattened structure which 
might be more efficient for retrievals.

image

**Comment by berezovskyi** [comment]
Hi Swarup,

I agree with you, preventing missions without an object type is best done at the MOO manager level than in the ontology.

The tree that you have drawn in a figure represents the examples correctly.

The tree may indeed contain nodes with multiple selectors. Here is an example: a `CompositeSelector` **A** has two selectors **B** & **C**. Selector **B** is a `CountSelector` as in the upper branch of your tree but **C** is _another_ `CompositeSelector`.

The reason why flattening is may be undesirable is that we have specific semantics attached to the nested selectors: a selector narrows down the results of the child selector. I will give an example from the tree you have drawn. In the upper branch, we will first limit our selection a certain shelf, next we will narrow down to the objects of a certain type on that shelf and then take a certain number of them. If you were to change the hierarchy to first filter by shelf, then take a certain number of objects with a count selector and finally filter by type at the top level, we would get two different result sets.

/Andrew

**Comment by berezovskyi** [comment]
@swarupmohalik we just had another look at it with @likelion and moved it under the warehouse controller. we also removed the base from the turtle file to make less problems for Prolog when parsing this.

I will use this file to start generating the warehouse controller REST adaptor skeleton. If we encounter issues, we can amend this file with you and @likelion.

Shall we merge?

**Comment by berezovskyi** [comment]
Please see https://github.com/EricssonResearch/scott-eu/issues/40#issuecomment-346022243 for how this ontology will be used in the WHC.

**Comment by swarupmohalik** [comment]
Yes Andrii. makes sense. Please go ahead.
I have some clarification text in #40

**Pull request merged**
