### PR TITLE
WIP: simple broker and producer/consumer example in python

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
Why not use http://emqtt.io/docs/v2/install.html#install-via-docker-image or even simpler https://hub.docker.com/r/devicexx/emqttd/?

**Comment by berezovskyi** [comment]
@likelion what shall we do with this one? we already have config for mosquitto but emq is much more scalable.

**Comment by likelion** [comment]
@berezovskyi I have no clue. You decide.

**Comment by berezovskyi** [comment]
@swarupmohalik @ricardossouza @likelion I am abandoning it for now but keeping the branch. Tell me if you want me to get this patch updated and merged.

**Pull request closed without merging**
