### PR TITLE
Issue 122

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by jramadeu** [comment]
I may vote is to don't merge this branch as well. All its commits but commits [4f5d46d](https://github.com/EricssonResearch/scott-eu/commit/4f5d46d0fdf89d1b8bd9ced20e88c840e3bf9b18), [787f313304](https://github.com/EricssonResearch/scott-eu/commit/787f313304ca43aa2ac21bbc6008b4ef85bef0bf) and [7d012008](https://github.com/EricssonResearch/scott-eu/commit/7d0120081f92cfa3b5b21b72202c98020341030e) are in the already merged branch_116.

@albertohata , please review those commits and make a decision.

**Comment by berezovskyi** [comment]
@albertohata shall we close?

**Comment by berezovskyi** [comment]
@albertohata shall we close?

**Comment by albertohata** [comment]
> @albertohata shall we close?

yes, we can close it

**Pull request closed without merging**
