### PR TITLE
Soar agents

### PR DESCRIPTION
**Pull request by berezovskyi**
We need to merge this branch or delete it.

### CODE REVIEW

**Comment by jramadeu** [comment]
Can we close this? I think this branch was merged on the #108 

We just need a clean some branches including this one.

**Comment by berezovskyi** [comment]
wait, I was too fast. #108 included `soar_ros` which was merged into `soar_ros_trial` but this one is named agent, not ROS

@ricardossouza what do you think?

**Comment by jramadeu** [comment]
> wait, I was too fast. #108 included `soar_ros` which was merged into `soar_ros_trial` but this one is named agent, not ROS

Better ask to @KRaizer

**Comment by KRaizer** [comment]
Branch  soar-agents is an older approach to implementing the soar agents and can be removed.

**Pull request closed without merging**
