### PR TITLE
WIP: An initial gateway implementation

### LINKED ISSUE #107: Figure out the extensibility mechanism for the Gateway Backend
I initially thought of OSGi.

Leo has suggested loading a JAR at runtime: https://stackoverflow.com/questions/60764/how-should-i-load-jars-dynamically-at-runtime But this approach would require to scan the whole JAR, load its each of its classes etc: https://stackoverflow.com/questions/45166757/loading-classes-and-resources-in-java-9 and https://stackoverflow.com/questions/41932635/scanning-classpath-modulepath-in-runtime-in-java-9

Then I have recalled of https://docs.oracle.com/javase/9/docs/api/java/util/ServiceLoader.html class and found the guide https://docs.oracle.com/javase/tutorial/ext/basics/spi.html#introduction. The guide only requires to put a JAR on the classpath at the application startup. Why not? We can put the JAR into a Docker volume that gets copied to the `/lib/ext` and Jetty will put it on the classpath at the startup: https://www.eclipse.org/jetty/documentation/9.4.x/startup-classpath.html

### PR DESCRIPTION
**Pull request by berezovskyi**
The initial implementation uses PyZMQ and JeroMQ in the [ZMQ_DEALER](http://api.zeromq.org/2-1:zmq-socket#toc6) mode that allows a single socket to be used for non-blocking bidirectional communication between two nodes with a certain buffer control until the calls become blocking (1000 pending messages on my machine).

Closes #107, the JARs are loaded through a Java SE `ServiceLocator` mechanism.

### CODE REVIEW

**Comment by berezovskyi** [comment]
@rssouza feel free to add more commits here! The ZMQ part is working OK. What has to be done:

- [ ] Send and receive messages in separate threads to avoid hitting the ZMQ buffer "water mark"
- [ ] Either switch the code to use msgpack or switch the Gateway spec to use JSON (we'll have to do base64 encoding of the `msgBody` in that case and I'd prefer to avoid that)
- [ ] Define a Java interface for the loaded services
- [ ] Wrap the backend in an OSLC Server
- [ ] Implement service loading on the backend
- [ ] Expose a TRS Server on the Gateway
- [ ] Package the Backend as a Docker image that GW Frontend developers can build their images FROM 

@likelion would be great if you can review this PR but it's too raw at this stage, I will ping you when it's ready.

**Comment by berezovskyi** [comment]
Also, not sure if the [ZMQ_PAIR](http://api.zeromq.org/2-1:zmq-socket#toc15) is a better option than the ZMQ_DEALER.

**Comment by berezovskyi** [comment]
@likelion @rssouza the last commit includes my initial shot at loading OSLC resource classes as well as the (un)marshalling classes dynamically via classpath. I think the general concept is ready for your design review. I will chat with @jadelkhoury tomorrow how can we build an OSLC server dynamically from that.

**Comment by likelion** [comment]
@berezovskyi Looks good to me, pretty straight-forward, I didn't try to run it though. Maybe a Dockerfile would be helpful here...

**Review by likelion — APPROVED** [review]

**Comment by berezovskyi** [comment]
@likelion a few Dockerfiles are coming! But first I need to turn the backend into a webapp. Just had a good chat with @jadelkhoury and we narrowed the scope on it pretty well.

**Comment by berezovskyi** [comment]
@likelion the deploy is fixed now.

But we have been hit by #150 after JAX-RS 2.0 supported was merged into master in Lyo.

**Comment by berezovskyi** [comment]
@rssouza I rebased this on master and squashed some commits. If you wish, we can merge this now is and open a new issue for the TODOs. Or, if you think there is no risk of merge conflicts later, we can keep it open until we have something more functional.

**Pull request merged**
