### PR TITLE
WIP: Update Lyo Sandbox for the paper & June demo

### LINKED ISSUE #95: Remove Leshan from the sandbox

### PR DESCRIPTION
**Pull request by berezovskyi**
Closes #95 

---

This change is [Reviewable](https://reviewable.io/reviews/ericssonresearch/scott-eu/72)

### CODE REVIEW

**Comment by swarupmohalik** [comment]
Getting this error with sandbox-twin. The sandbox-warehouse URI seems ok.

sandbox-twin_1             | [main] ERROR org.apache.wink.server.internal.servlet.RestServlet - org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingAnnotationException: OSLC008: Missing mandatory OSLC annotation org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape for class java.net.URI
sandbox-twin_1             | org.apache.wink.common.internal.lifecycle.ObjectCreationException: org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingAnnotationException: OSLC008: Missing mandatory OSLC annotation org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape for class java.net.URI
sandbox-twin_1             | 	at org.apache.wink.common.internal.lifecycle.CreationUtils.createObject(CreationUtils.java:76)
sandbox-twin_1             | 	at org.apache.wink.common.internal.lifecycle.LifecycleManagerUtils.createSingletonObjectFactory(LifecycleManagerUtils.java:61)
sandbox-twin_1             | 	at org.apache.wink.common.internal.lifecycle.DefaultLifecycleManager.createObjectFactory(DefaultLifecycleManager.java:83)
sandbox-twin_1             | 	at org.apache.wink.common.internal.lifecycle.LifecycleManagersRegistry.getObjectFactory(LifecycleManagersRegistry.java:85)
sandbox-twin_1             | 	at org.apache.wink.server.internal.servlet.RestServlet.getApplication(RestServlet.java:249)
sandbox-twin_1             | 	at org.apache.wink.server.internal.servlet.RestServlet.createRequestProcessor(RestServlet.java:129)
sandbox-twin_1             | 	at org.apache.wink.server.internal.servlet.RestServlet.init(RestServlet.java:94)
sandbox-twin_1             | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.start(Server.java:452)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1515)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1439)
sandbox-twin_1             | 	at java.security.AccessController.doPrivileged(Native Method)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1438)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sandbox-twin_1             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sandbox-twin_1             | 	at java.lang.reflect.Method.invoke(Method.java:498)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.start(Main.java:506)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.main(Main.java:78)
sandbox-twin_1             | Caused by: org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingAnnotationException: OSLC008: Missing mandatory OSLC annotation org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape for class java.net.URI
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createResourceShape(ResourceShapeFactory.java:121)
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createProperty(ResourceShapeFactory.java:300)
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createResourceShape(ResourceShapeFactory.java:153)
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.core.model.ResourceShapeFactory.createResourceShape(ResourceShapeFactory.java:110)
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.application.OslcResourceShapeResource.<init>(OslcResourceShapeResource.java:65)
sandbox-twin_1             | 	at org.eclipse.lyo.oslc4j.application.OslcWinkApplication.<init>(OslcWinkApplication.java:56)
sandbox-twin_1             | 	at se.ericsson.cf.scott.sandbox.servlet.Application.<init>(Application.java:150)
sandbox-twin_1             | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sandbox-twin_1             | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sandbox-twin_1             | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
sandbox-twin_1             | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
sandbox-twin_1             | 	at org.apache.wink.common.internal.lifecycle.CreationUtils.createObject(CreationUtils.java:66)
sandbox-twin_1             | 	... 51 more
sandbox-twin_1             | 2018-04-04 07:43:27.734:WARN:oejshC.sandbox_twin:main: unavailable
sandbox-twin_1             | javax.servlet.UnavailableException: org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingAnnotationException: OSLC008: Missing mandatory OSLC annotation org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape for class java.net.URI
sandbox-twin_1             | 	at org.apache.wink.server.internal.servlet.RestServlet.init(RestServlet.java:111)
sandbox-twin_1             | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.start(Server.java:452)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1515)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1439)
sandbox-twin_1             | 	at java.security.AccessController.doPrivileged(Native Method)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1438)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sandbox-twin_1             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sandbox-twin_1             | 	at java.lang.reflect.Method.invoke(Method.java:498)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.start(Main.java:506)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.main(Main.java:78)
sandbox-twin_1             | 2018-04-04 07:43:27.735:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@4e9ba398{/sandbox-twin,file:///tmp/jetty/jetty-0.0.0.0-8080-sandbox-twin.war-_sandbox-twin-any-6689660910719143665.dir/webapp/,UNAVAILABLE}{/sandbox-twin.war}
sandbox-twin_1             | javax.servlet.UnavailableException: org.eclipse.lyo.oslc4j.core.exception.OslcCoreMissingAnnotationException: OSLC008: Missing mandatory OSLC annotation org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape for class java.net.URI
sandbox-twin_1             | 	at org.apache.wink.server.internal.servlet.RestServlet.init(RestServlet.java:111)
sandbox-twin_1             | 	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:637)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:421)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:760)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:348)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1501)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1463)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
sandbox-twin_1             | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
sandbox-twin_1             | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:502)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:447)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
sandbox-twin_1             | 	at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:564)
sandbox-twin_1             | 	at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:239)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.start(Server.java:452)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
sandbox-twin_1             | 	at org.eclipse.jetty.server.Server.doStart(Server.java:419)
sandbox-twin_1             | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1515)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1439)
sandbox-twin_1             | 	at java.security.AccessController.doPrivileged(Native Method)
sandbox-twin_1             | 	at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1438)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sandbox-twin_1             | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sandbox-twin_1             | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
sandbox-twin_1             | 	at java.lang.reflect.Method.invoke(Method.java:498)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.invokeMain(Main.java:221)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.start(Main.java:506)
sandbox-twin_1             | 	at org.eclipse.jetty.start.Main.main(Main.java:78)

**Comment by berezovskyi** [comment]
Thanks for giving it a try, @swarupmohalik. The robot twin is not working yet, that is expected. But the shelf twin should work for you. Please try.

**Comment by swarupmohalik** [comment]
Andrii,
I wanted to tryout the robot twin fix. Make gives the following error.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sandbox-parent ..................................... SUCCESS [  0.085 s]
[INFO] Sandbox PPDL Domain ................................ SUCCESS [  1.406 s]
[INFO] webapp-whc ......................................... FAILURE [01:12 min]
[INFO] webapp-twin ........................................ SKIPPED
[INFO] webapp-twin-shelf .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2018-04-13T11:05:58+05:30
[INFO] Final Memory: 26M/566M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project webapp-whc: Could not resolve dependencies for project se.ericsson.cf.scott.sandbox:webapp-whc:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.lyo.trs:trs-consumer:jar:2.4.0-SNAPSHOT, org.eclipse.lyo.trs:trs-server:jar:2.4.0-SNAPSHOT: Could not find artifact org.eclipse.lyo.trs:trs-consumer:jar:2.4.0-SNAPSHOT in lyo-snapshots (https://repo.eclipse.org/content/repositories/lyo-snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :webapp-whc
Makefile:2: recipe for target 'up' failed
make: *** [up] Error 1

**Comment by berezovskyi** [comment]
Ah yes, you are correct, these two need to be installed manually as I have not yet contributed changes to the original libraries.

–Andrew.
(sent from my phone)

**Comment by berezovskyi** [comment]
@swarupmohalik you (and @rssouza) will need to do extra steps:

1. Clone https://github.com/eclipse/lyo-trs-server/tree/mqtt ('mqtt' branch)
2. install it by running `mvn clean install` in the root folder.
1. Clone https://github.com/eclipse/lyo-trs-client/tree/mqtt ('mqtt' branch)
2. install it by running `mvn clean install` in the root folder.

Then the twin fix should work.

**Comment by berezovskyi** [comment]
We finally got the connection from the twin to ROS master working:

image

And the build succeeds on @rssouza  machine.

**Comment by berezovskyi** [comment]
Close in favour of #99 w/o merging

**Pull request closed without merging**
