### PR TITLE
Add a ROS Service for the comms b/w the ROS Node & twin

### PR DESCRIPTION
**Pull request by berezovskyi**
This is an attempt to generate the necessary code for the integration with Java. Unfortunately, I did not see the source Java files but only a Maven repo, so I have deployed it at KTH. Please find the conn details on Slack or message me individually.

This particular patch was developed on my VM while @albertohata was remotely assisting me.

The patch is not fully working yet because the Maven repository generated using the 

    genjava_message_artifacts --verbose

command is still not producing a Maven repo that works flawlessly:

```
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project se.ericsson.cf.scott.sandbox:webapp-twin:war:0.0.1-SNAPSHOT: Failed to collect dependencies at org.ros.rosjava_messages:turtlebot2i_warehouse:jar:0.0.1 -> org.ros.rosjava_bootstrap:message_generation:jar:[0.3,0.4)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 24 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.ros.rosjava_messages:turtlebot2i_warehouse:jar:0.0.1 -> org.ros.rosjava_bootstrap:message_generation:jar:[0.3,0.4)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
	... 25 more
Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for org.ros.rosjava_bootstrap:message_generation:jar:[0.3,0.4) within specified range
```

The repo only has packages under the `org.ros.rosjava_messages` group, but nothing under the `org.ros.rosjava_bootstrap` group.

### CODE REVIEW

**Comment by berezovskyi** [comment]
The problem was solved by also adding https://github.com/rosjava/rosjava_mvn_repo/raw/master repo to the mix.

**Comment by berezovskyi** [comment]
The Java side could connect to any service:

```
[pool-1-thread-1] INFO org.ros.internal.node.client.Registrar -
MasterXmlRpcEndpoint URI: http://localhost:11311 [pool-1-thread-6] INFO
org.ros.internal.node.client.Registrar - Registering publisher:
Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</rosjava_tutorial_services/client,
http://localhost:51970/>, TopicIdentifier</rosout>>,
Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log,
acffd30cd6b6de30f120938c17c593fb>>>> [pool-1-thread-9] INFO
org.ros.internal.node.client.Registrar - Response<Success, Registered
[/rosjava_tutorial_services/client] as publisher of [/rosout],
[http://andrew-VirtualBox:45001/]> [pool-1-thread-7] INFO
org.ros.internal.node.topic.DefaultPublisher - Publisher registered:
Publisher<PublisherDefinition<PublisherIdentifier<NodeIdentifier</rosjava_tutorial_services/client,
http://localhost:51970/>, TopicIdentifier</rosout>>,
Topic<TopicIdentifier</rosout>, TopicDescription<rosgraph_msgs/Log,
acffd30cd6b6de30f120938c17c593fb>>>> [pool-1-thread-3] INFO
se.ericsson.cf.scott.sandbox.twin.ros.RobotClientNode - RobotClientNode started
[pool-1-thread-3] ERROR se.ericsson.cf.scott.sandbox.twin.ros.RobotClientNode -
ROS exception org.ros.exception.ServiceNotFoundException: No such service
/TaskRequestService of type turtlebot2i_warehouse/TaskRequest
	at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:356)
	at org.ros.internal.node.DefaultNode.newServiceClient(DefaultNode.java:372)
	at
	se.ericsson.cf.scott.sandbox.twin.ros.RobotClientNode.onStart(RobotClientNode.java:33)
	at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:507) at
	org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:504) at
	org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43) at
	org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56) at
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by berezovskyi** [comment]
cc @rssouza

**Comment by berezovskyi** [comment]
@likelion we might need to forward ephemeral ports too... https://answers.ros.org/question/9725/clarification-on-ross-port-usage/ any ideas? I hope not something like https://stackoverflow.com/a/43165464/464590

**Review by ricardossouza — APPROVED** [review]

**Pull request merged**
