### PR TITLE
Implementation of OSLC library for Prolog

### PR DESCRIPTION
**Pull request by likelion**
Still work in progress... everyone is welcome to ask questions! See #16.

### CODE REVIEW

**Comment by likelion** [comment]
Ok, it seems I'm ready to release an alpha version. It has support for programmatic OSLC resource manipulation, and custom OSLC service definition (via declaring `oslc_*` handlers with priorities), basic REST resource operations (POST to creation factory, PUT with matching `If-Match` header, GET with `oslc.properties` and `oslc.prefix` parameters, and DELETE). Resource shape validation supports occurs and type checks. REST interface supports all RDF+XML and TURTLE content types on both input and output. Brief API documentation is available at:

`http://localhost:3020/help/source/doc/_CWD_/cpack/oslc_prolog/lib/oslc.pl`

**Comment by likelion** [comment]
Current OSLC core implementation is a REST service that exposes OSLC resources at

`http://<host>:<port>/<prefix>/<resource>`

, where `<prefix>` is an IRI prefix defined in Prolog using `rdf_register_prefix/3` (or in Manifest.ttl file using `lib:Namespace` object), and `<resource>` is an OSLC local resource name. For example, a GET request to the following URI will return `oslc:ResourceShape` resource:

`http://localhost:3020/oslc/ResourceShape`

**Comment by likelion** [comment]
### Current API for manipulating OSLC resources:

screen shot 2017-07-25 at 16 25 38

**Comment by likelion** [comment]
### Future work:

- [ ] optimize `copy_resource/5` using dictionaries and make it default resource shape validator
- [ ] implement properer exception handling and error reporting using `oslc:Error`
- [ ] implement validation of `oslc:range`, `oslc:allowedValue` and `oslc:maxSize`
- [ ] resource paging
- [ ] create API for OSLC clients in Prolog
- [ ] write a complete set of unit tests

### Bonus features:

- [ ] implement query strings for Query Capability's base URI
- [ ] authentication mechanisms (basic, OAuth, form)
- [ ] support for JSON representation of OSLC Defined Resources
- [ ] UI previews
- [ ] Delegated User Interface Dialogs

**Review by berezovskyi — APPROVED** [review]

**Pull request merged**
