### PR TITLE
Add the NLP component

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
@likelion @eanevul seems like all of the code from Blackburn for the NLP is under GPL. What do we do with this?

@bluelancer there is no README. How do I run the code? What are the dependencies? Do you think you could add a README and maybe a Dockerfile, please?

**Comment by berezovskyi** [comment]
@bluelancer @likelion this is how I am trying to run it:

```
> swipl -s parseRDF.pl
Warning: /Users/andrew/kth/scott/scott/misc/NLP/source/parseRDF.pl:47:
Warning:    Clauses of parseRDF:find_text/2 are not together in the source-file
Warning:    Earlier definition at /Users/andrew/kth/scott/scott/misc/NLP/source/parseRDF.pl:21
Warning:    Current predicate: parseRDF:first_atom_uppercase/2
Warning:    Use :- discontiguous parseRDF:find_text/2. to suppress this message
Welcome to SWI-Prolog (threaded, 64 bits, version 8.1.9)
```

**Comment by berezovskyi** [comment]
NB! Run it with `swipl -s lambda.pl`.

@bluelancer the `sentence/2` predicate is defined in `sentenceTestSuite` module but there is no file `sentenceTestSuite,pl` in the folder. Do you have any such file on your disk?

**Comment by bluelancer** [comment]
Fast fix, I will check up my repo later tonight ☺

Sorry for the issue.
Yifei

**Pull request closed without merging**
