### PR TITLE
WIP: Simulation ros

### PR DESCRIPTION
**Pull request by berezovskyi**
This change is [Reviewable](https://reviewable.io/reviews/ericssonresearch/scott-eu/73)

### CODE REVIEW

**Comment by berezovskyi** [comment]
From https://github.com/EricssonResearch/scott-eu/blob/simulation-ros/simulation-ros/doc/architecture.md#2-architecture how does VREP send ROS messages to the robots if they  don't share a common master?

**Comment by jramadeu** [comment]
Indeed that's a good question.

I think we need to rethink this. In the way things are showed on the diagram, it's impossible to communicate between different ROS nodes and VREP.

Is that the case, that on simulation we just have _one_ rosmaster running on V-REP machine's? And the scenario with one rosmaster for each robot it's with real robots?

What do you think guys? @albertohata @KRaizer @rssouza

**Comment by berezovskyi** [comment]
I imported this PR to Reviewable https://reviewable.io/reviews/EricssonResearch/scott-eu/73#- becase Github is not handling half a thousand files well.

**Comment by berezovskyi** [comment]
Review status: 0 of 434 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8vy63phZ4APisO2G:-L6v8vy63phZ4APisO2H:b3g2bk1) (no related file):*
I think you should use this gitignore https://github.com/github/gitignore/blob/master/ROS.gitignore

---

*[simulation-ros/devel/.built_by, line 1 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8NcS5qzS4Mu8UJNC:-L6v8NcT7Dx_nRut-EnI:bms2rl7) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.built_by#L1)):*
> ```
> catkin_make
> ```

is it an autogerated file?

---

*[simulation-ros/devel/.catkin, line 1 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8TyL0OGuMMBGaCvc:-L6v8TyL0OGuMMBGaCvd:b-jrb9xe) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.catkin#L1)):*
> ```
> /home/eznasam/project/scott-eu/simulation-ros/src
> ```

not sure this file shall be here

---

*[simulation-ros/devel/.rosinstall, line 2 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8XmOAXbFnWfUqvPL:-L6v8XmOAXbFnWfUqvPM:b-3lt8q4) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.rosinstall#L2)):*
> ```
> - setup-file:
>     local-name: /home/eznasam/project/scott-eu/simulation-ros/devel/setup.sh
> ```

same, not sure you should commit this folder

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73)*

**Comment by KRaizer** [comment]
@jramadeu 
As I recall, we discussed this issue during our last meeting here. The conclusion was that we had to update the diagram to make it clear the difference between the two options: 1) everything working in simulation, 2) real robots + simulation
We had two ideas at the time: a) creating one separate diagram for each case, b) leave both cases in a single diagram, but with different colors.

**Comment by berezovskyi** [comment]
cc @rafiainam

**Comment by jramadeu** [comment]
Yes, when I was writing my previous message I also remembered our discussion. So, we can say that:

1) In simulation:
Only one rosmaster being executed on the vrep machine's. No rosmater inside simulated robot (btw, the vrep is the robot =p)

2) In real robots:
Each robot has his own master.

In my opinion, and we have discussed this, I think the best option it's to put in red all boxes that are used only in simulation, in blue the ones used only with real robot. 

---

Review status: 0 of 434 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8vy63phZ4APisO2G:-L6vBuz4BHgGWecocG88:b-kmr42a) (no related file):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

I think you should use this gitignore https://github.com/github/gitignore/blob/master/ROS.gitignore
</blockquote></details>

I agree. Didn't realize all the trash on the repo.

---

*[simulation-ros/devel/.built_by, line 1 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8NcS5qzS4Mu8UJNC:-L6vAz0RDesn-J5yiAB7:bw0rwew) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.built_by#L1)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

is it an autogerated file?
</blockquote></details>

Yes... We should use that gitignore that you suggested.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-:-L6vBfjmEghkI4s1RilU:b-1xh5lv)*

**Comment by berezovskyi** [comment]
Thanks @jramadeu. How does a CB twin  interface a simulated conveyor belt in VREP?

–Andrew.
(sent from my phone)

**Comment by jramadeu** [comment]
Sorry about about know what is a CB twin. 

But if we want to interface a conveyor belt in VREP, I see two ways of doing it:

1) Direct access to the conveyor belt via V-REP Remote API (JAVA, C++, Python...)

2) Create a ROS Node in a similar way to the robots 

---

Review status: 0 of 434 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-:-L6xUQEDDJyro4o5-RhM:b-4ywru1)*

**Comment by jramadeu** [comment]
Sorry... Last message was poorly written. Translating that to English: "I don´t know what is a CB twin"

---

Review status: 0 of 434 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-:-L6xWbvx7CSE2QQERnz1:bozt1tq)*

**Comment by berezovskyi** [comment]
Sorry, it’s a conveyor belt twin.

–Andrew.
(sent from my phone)

**Comment by berezovskyi** [comment]
Review status: 0 of 438 files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L6v8vy63phZ4APisO2G:-L74nuafuaGcEPGPFH5d:b-12nvgj) (no related file):*
<details><summary><i>Previously, jramadeu wrote…</i></summary><blockquote>

I agree. Didn't realize all the trash on the repo.
</blockquote></details>

please run `git ls-files --ignored --exclude-standard | xargs git rm --cached` and push the change to remove the newly ignored files

---

*[simulation-ros/doc/architecture.md, line 26 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74oJYwb8m1SoQhX2Og:-L74oJYwb8m1SoQhX2Oh:b-31f7ca) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/doc/architecture.md#L26)):*
> ```Markdown
> 
> 
> alt text
> ```

not a real URL I think :)

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/CMakeLists.txt, line 1 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74p-6ax1XDEZ6Tmind:-L74p-6ax1XDEZ6Tmine:biop6kc) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/CMakeLists.txt#L1)):*
> ```CMake
> cmake_minimum_required(VERSION 2.4.6)
> ```

do you think we can add this to the Travis build config?

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/Makefile, line 1 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74pETFOb8UxFgD8LJn:-L74pETFOb8UxFgD8LJo:b-n5plkt) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/Makefile#L1)):*
> ```Makefile
> include $(shell rospack find mk)/cmake.mk
> ```

hmm, installing rospack in Travis/etc is a start

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 7 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74pacldNOrbzTNRVsb:-L74pacmLYS5SqSuQJ7r:b3iqyxf) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml#L7)):*
> ```XML
> 
>   </description>
>   <author>Alberto</author>
> ```

Alberto Hata?

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 8 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74pO8RWhlxYJqKZ0y4:-L74pO8RWhlxYJqKZ0y5:b-b4woz) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml#L8)):*
> ```XML
>   </description>
>   <author>Alberto</author>
>   <license>BSD</license>
> ```

I think the repo license is Apache 2.  Or we don't care?

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 10 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74pZZjSVylhNmK2eMb:-L74pV-lgjYrBZJmwSjL:b-gt5uu8) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml#L10)):*
> http://ros.org/wiki/turtlebot2i_warehouse
does not exist yet

---

*[simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/scene.yaml, line 1 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74pwaRMu1bHJ-UcP6f:-L74pwaRMu1bHJ-UcP6g:b-hizcxy) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/scene.yaml#L1)):*
> ```YAML
> - node:
> ```

where did this file come from?

---

*[simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/external/pycpp/README.md, line 57 at r3](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73#-L74qJndU2fXZB1XrZVP:-L74qJndU2fXZB1XrZVQ:b-ww44gc) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/external/pycpp/README.md#L57)):*
> ```Markdown
> #py for i, item in enumerate(items):
> #py if item == items[-1]:
>     `item` = `factorial(i+1)`
> ```

Whoa that's very cool stuff!!! But why are we using it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ericssonresearch/scott-eu/73)*

**Comment by albertohata** [comment]
> please run git ls-files --ignored --exclude-standard | xargs git rm --cached and push the change to remove the newly ignored files

**Comment by berezovskyi** [comment]
Why did you close it @albertohata?

**Comment by albertohata** [comment]
Thanks @berezovskyi for your comments! My replies are below.

> a discussion (no related file):
> Previously, jramadeu wrote…
> 
> please run git ls-files --ignored --exclude-standard | xargs git rm --cached and push the change to remove the newly ignored files

I've added .gitignore file.

> simulation-ros/doc/architecture.md, line 26 at r3 (raw file):
> 
>     alt text
> 
> not a real URL I think :)

Thanks for noticing that. It was a merge error.

> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/CMakeLists.txt, line 1 at r3 (raw file):
> 
>     cmake_minimum_required(VERSION 2.4.6)
> 
> do you think we can add this to the Travis build config?

Never used Travis build, but this may be considered.

> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/Makefile, line 1 at r3 (raw file):
> 
>     include $(shell rospack find mk)/cmake.mk
> 
> hmm, installing rospack in Travis/etc is a start
> 
> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 7 at r3 (raw file):
> 
>       </description>
>       <author>Alberto</author>
> 
> Alberto Hata?

I'll include this also.

> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 8 at r3 (raw file):
> 
>       </description>
>       <author>Alberto</author>
>       <license>BSD</license>
> 
> I think the repo license is Apache 2. Or we don't care?

This information came from the file that I copied. I will update it.

> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/manifest.xml, line 10 at r3 (raw file):
> 
>     http://ros.org/wiki/turtlebot2i_warehouse
>     does not exist yet

This was automatically generated by ROS. I will remove that.

> simulation-ros/src/turtlebot2i/turtlebot2i_warehouse/scene.yaml, line 1 at r3 (raw file):
> 
>     - node:
> 
> where did this file come from?

This file I will use to store the topological map of the warehouse scenario.

> simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/external/pycpp/README.md, line 57 at r3 (raw file):
> 
>     #py for i, item in enumerate(items):
>     #py if item == items[-1]:
>         `item` = `factorial(i+1)`
> 
> Whoa that's very cool stuff!!! But why are we using it here?

Indeed very amazing! This file actually belongs to v_repStubsGen which is required by V-REP ROS Interface.

**Comment by albertohata** [comment]
> Why did you close it @albertohata?

@berezovskyi I think it was closed automatically by github :/
Sorry, it was not my intention...

**Comment by albertohata** [comment]
@berezovskyi Regards to the architecture, I've updated the figure and the description. However, it is still not complete. Any comments are welcome

**Comment by albertohata** [comment]
@berezovskyi, I still not able to merge pull request. It seems that a review is still required...

**Comment by berezovskyi** [comment]
Reviewed 162 of 440 files at r1, 1 of 2 files at r2, 23 of 48 files at r3, 2 of 186 files at r4, 1 of 2 files at r5, 38 of 107 files at r6, 12 of 13 files at r7.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8vy63phZ4APisO2G:-L75DRCDgRkfw2sRTbTT:b-ucfknh) (no related file):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

please run `git ls-files --ignored --exclude-standard | xargs git rm --cached` and push the change to remove the newly ignored files
</blockquote></details>

Thanks!

---

*[simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml, line 3 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R0P7e7Lr0ZrTbOsM_:-L9R0P7e7Lr0ZrTbOsMa:budx1jl) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml#L3)):*
> ```
> phantomx_pincher_arm_description
> ```

can use git submodules instead of vendoring the whole folder?

https://github.com/Interbotix/phantomx_pincher_arm

---

*[simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml, line 16 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R08D-3iqviWmhR13e:-L9R08D-3iqviWmhR13f:b-cyce4z) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml#L16)):*
> ```
> TODO
> ```

we need a real license here

---

*[simulation-ros/src/turtlebot2i/README.md, line 3 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R0sOw0GCn7BMsln7m:-L9R0sOw0GCn7BMsln7n:b-2hl5uh) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/turtlebot2i/README.md#L3)):*
> ```
> turtlebot2i
> ```
 
same, can we do a git submodule here?

https://github.com/Interbotix/turtlebot2i

---

*[simulation-ros/src/vrep_ros_interface/CMakeLists.txt, line 1 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R13xT7_yFipON9pOA:-L9R13xT7_yFipON9pOB:butpd7j) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/vrep_ros_interface/CMakeLists.txt#L1)):*
> ```CMake
> cmake_minimum_required(VERSION 2.8.3)
> ```

again, same thing: let's use submodules!

---

*[simulation-ros/src/vrep_ros_interface/package.xml, line 2 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9FtQu47I2lGV13nlqs:-L9FtQu47I2lGV13nlqt:b-racaut) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/vrep_ros_interface/package.xml#L2)):*
> ```
> vrep_ros_interface
> ```

---

*[simulation-ros/devel/.built_by, line 1 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8NcS5qzS4Mu8UJNC:-L75DihIBL_HAkMZP2Er:b-896fix) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.built_by#L1)):*
<details><summary><i>Previously, jramadeu wrote…</i></summary><blockquote>

Yes... We should use that gitignore that you suggested.
</blockquote></details>

Done.

---

*[simulation-ros/devel/.catkin, line 1 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8TyL0OGuMMBGaCvc:-L75DeztjKa6en87PF-c:b-896fix) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.catkin#L1)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

not sure this file shall be here
</blockquote></details>

Done.

---

*[simulation-ros/devel/.rosinstall, line 2 at r1](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L6v8XmOAXbFnWfUqvPL:-L75Dg9wPaNBRRQThgb4:b-896fix) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/b93bedb6ded23d6f7044d07ec03fc0665f1781ab/simulation-ros/devel/.rosinstall#L2)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

same, not sure you should commit this folder
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73)*

**Comment by berezovskyi** [comment]
@albertohata that's the point, someone needs to review it :)

And about licenses: you must NEVER change the license that was put there by someone else. BSD licenses are fully OK. The ROS package either needs to be updated from the original repo to include the BSD license, or you should switch all packages (where possible) to use submodules.

once we resolve the license questions, I will +1 this. we can check how the code works later when we integrate with my branch.

**Comment by jramadeu** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml, line 3 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R0P7e7Lr0ZrTbOsM_:-L9R2mSa4fnmXGjoJ8Zk:b-fogb8) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml#L3)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

> ```
> phantomx_pincher_arm_description
> ```

can use git submodules instead of vendoring the whole folder?

https://github.com/Interbotix/phantomx_pincher_arm
</blockquote></details>

Hm... I think we can't use submodule because this's a modified version of the original repo hosted on github. We have an internal repository with the modifications and we keep that here using subtree. Is it a better practice to switch to submodule? 

---

*[simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml, line 16 at r6](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L9R08D-3iqviWmhR13e:-L9R4PY17ozCsp7W96Ed:b2nha9w) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/47a1a6d912d3ec637c2c54f45e720e5e5bded828/simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml#L16)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

> ```
> TODO
> ```

we need a real license here
</blockquote></details>

ACK

---

*[simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/external/pycpp/README.md, line 57 at r3](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73#-L74qJndU2fXZB1XrZVP:-L75-c3uE5cCm0LpP3tp:b-s9d1sf) ([raw file](https://github.com/ericssonresearch/scott-eu/blob/e96841c94238a4847d654a3e6706f50520bb2e62/simulation-ros/src/vrep_ros_interface/external/v_repStubsGen/external/pycpp/README.md#L57)):*
<details><summary><i>Previously, berezovskyi (Andrew Berezovskyi) wrote…</i></summary><blockquote>

Whoa that's very cool stuff!!! But why are we using it here?
</blockquote></details>

This is used by the vrep_ros_interface.

If I'm not mistake this is used by the vrep_ros_interface to generate an interface between C++ and Lua Functions. This's a wild guess. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/ericssonresearch/scott-eu/73)*

**Comment by albertohata** [comment]
> simulation-ros/src/phantomx_pincher_arm/phantomx_pincher_arm_description/package.xml, line 3 at r6 (raw file):
> Previously, berezovskyi (Andrew Berezovskyi) wrote…
> 
>         phantomx_pincher_arm_description
> 
>     can use git submodules instead of vendoring the whole folder?
> 
>     https://github.com/Interbotix/phantomx_pincher_arm
> 
> Hm... I think we can't use submodule because this's a modified version of the original repo hosted on github. We have an internal repository with the modifications and we keep that here using subtree. Is it a better practice to switch to submodule?

> simulation-ros/src/turtlebot2i/README.md, line 3 at r6 (raw file):
> 
>     turtlebot2i
> 
> same, can we do a git submodule here?
> 
> https://github.com/Interbotix/turtlebot2i

Same as in the case of the phantomx_pincher_arm, we are using our own turtlebot2i package. We are not using the code from Interbotix repository (until now). 
 
> simulation-ros/src/vrep_ros_interface/CMakeLists.txt, line 1 at r6 (raw file):
> 
>     cmake_minimum_required(VERSION 2.8.3)
> 
> again, same thing: let's use submodules!

In this case, the vrep_ros_interface has slight changes from the original source, such as support for other turtlebot2i messages.

**Comment by albertohata** [comment]
@berezovskyi have you any idea how to fix the following problem?

> continuous-integration/travis-ci/push — The Travis CI build failed

**Comment by berezovskyi** [comment]
@albertohata did you look at the build output (via the Details link)? I will take a look now

**Comment by berezovskyi** [comment]
Okay, a had a quick look. Seems like it's due to #62

**Comment by berezovskyi** [comment]
Re: "custom" packages – how custom is custom? Did you base your code on theirs (ie forked it)? Does it make sense to actually fork each of the repos and make changes on a branch there and:

1. track those branches from submodules
2. submit your changes back to the original repos

**Comment by albertohata** [comment]
> Re: "custom" packages – how custom is custom? Did you base your code on theirs (ie forked it)? Does it make sense to actually fork each of the repos and make changes on a branch there and:
> 
>     track those branches from submodules
>     submit your changes back to the original repos

The "custom" is in the sense that some of the packages are derived from packages of other repositories. An example is the turtlebot2i_description package which uses the turtlebot2i 3D models of the manufacturer repository. As just some of the files are reused don't know if forking the whole repo is necessary. What do you think?  (An exception is the vrep_ros_interface package which maybe makes sense forking it.)

**Comment by berezovskyi** [comment]
@likelion what's your opinion?

**Comment by berezovskyi** [comment]
won't merge; see #110

**Pull request closed without merging**
