### PR TITLE
Merge Docker Compose configs & Move Lyo components to the top level

### PR DESCRIPTION
**Pull request by berezovskyi**
#72 should be merged first and then the number of commits/files changes will drop drastically.

this patch basically:

* updates lyo compose config from v2 to v3.3
* merges it with planner_reasoner compose config
* moves all project subfolders not involved in the composed config to misc/ or to docs/

### CODE REVIEW

**Comment by berezovskyi** [comment]
@likelion I will need your help to test how this works with our CI pipeline internally

**Comment by berezovskyi** [comment]
and I like all three checks to get red right away :)

**Comment by berezovskyi** [comment]
@likelion you can use https://github.com/EricssonResearch/scott-eu/pull/98/files/fc169fa0fed1aea3b1afac81facbe6a221f31afa..1ca606e1d3b106c2987cd74e3b9e0183b86c28de to review the relevant subset of the patches

**Comment by likelion** [comment]
Looks like Metric-FF site is down... :( cannot build...

`--2018-07-17 09:22:44--  (try: 2)  https://fai.cs.uni-saarland.de/hoffmann/ff/Metric-FF-v2.0.tgz
Connecting to fai.cs.uni-saarland.de (fai.cs.uni-saarland.de)|134.96.226.3|:443... `

we may need to setup a mirror for it.

**Comment by likelion** [comment]
There seem to be another build problem according to Travis:

`[ERROR] Failed to execute goal on project webapp-whc: Could not resolve dependencies for project se.ericsson.cf.scott.sandbox:webapp-whc:war:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.lyo.trs:trs-client:jar:2.4.0-SNAPSHOT, org.eclipse.lyo.trs:trs-server:jar:2.4.0-SNAPSHOT: Could not find artifact org.eclipse.lyo.trs:trs-client:jar:2.4.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]`

**Comment by berezovskyi** [comment]
We do depend on the custom `mqtt` branches of https://github.com/eclipse/lyo.trs-client and https://github.com/eclipse/lyo.trs-server. I am now trying to rework the Dockerfile to be a multistage build and mvn install the right artifacts from source automatically.

**Comment by berezovskyi** [comment]
I will actually have to abandon this patch because Docker does not allow ../ references and I need to access "parent" POM files etc.

**Pull request closed without merging**
