### PR TITLE
Split the Swarm stack configs for deploy and dev envs

### PR DESCRIPTION
**Pull request by berezovskyi**

### CODE REVIEW

**Comment by berezovskyi** [comment]
Maybe @albertohata @jramadeu and @ricardossouza should pitch in with this one. Do you guys use Docker? Shall we dockerise more ROS-related parts? But not 100% important to solve that part right now in this patch.

@likelion if you want, we can remove from the deploy config everything that does not work, is not accessible for some reason etc. and then slowly fix it service by service.

**Comment by likelion** [comment]
@berezovskyi I think we should make the `master` branch deployable, so, yes, removing everything that breaks and adding things as they get fixed is a good strategy.

**Comment by berezovskyi** [comment]
@likelion but then, do you like the idea to split the dev and prod stack configs? Do you want me to clean up the prod config from the things that are currently not in use (I think almost everything except planner).

**Comment by likelion** [comment]
@berezovskyi we can just comment out unused stuff in prod config, one can uncomment pieces in their own branches and do manual deployment for that branch.

**Comment by likelion** [comment]
@berezovskyi ok, I just looked at the code and I see what you mean, that works too!

**Review by likelion — APPROVED** [review]

**Comment by likelion** [comment]
@berezovskyi There seems to be wrong docker repo chosen for push, see log from our GitLab:

```
$ make push
(cd planner_reasoner		&&	make push)
make[1]: Entering directory '/builds/scott/scott-eu/scott-eu/planner_reasoner'
docker push scott/planner-reasoner
The push refers to repository [docker.io/scott/planner-reasoner]
```

**Comment by berezovskyi** [comment]
Hmm, how would you fix that?

**Comment by likelion** [comment]
@berezovskyi maybe we need to do `docker login` in make...

**Comment by likelion** [comment]
@berezovskyi Ahh, of course, you replaced `image: ${CI_REGISTRY_IMAGE}/scott-planner-reasoner` with `image: scott/planner-reasoner` in `deployment/docker-compose.yml`. The `${CI_REGISTRY_IMAGE}` variable contained correct URI of the docker repo, and now it assumes `docker.io` instead.

**Comment by berezovskyi** [comment]
🤦‍♂️

**Comment by berezovskyi** [comment]
Can we supply this address from the command-line instead?

**Comment by jramadeu** [comment]
> 
> 
> Maybe @albertohata @jramadeu and @ricardossouza should pitch in with this one. Do you guys use Docker? Shall we dockerise more ROS-related parts? But not 100% important to solve that part right now in this patch.
> 
Better late than never... 

I don't use any docker. If you think worth to use docker on our side (ROS), please let us know the reasons so we can discuss it better. 

Maybe @ricardossouza can help on this one. He knows docker/containers better than me.

**Comment by konstantino** [comment]
Hey guys - been dockerizing quite a bit of ros + gazebo + deep q learning here -> https://github.com/EricssonResearch/tnmt/tree/master/docker . It may come in handy for you.

**Comment by berezovskyi** [comment]
Abandoned in favour of #133

**Pull request closed without merging**
